ALTER TABLE paypal_accounts
  ADD COLUMN IF NOT EXISTS max_calls_total BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_calls_daily BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS call_count_total BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS call_count_daily BIGINT DEFAULT 0;

ALTER TABLE stripe_configs
  ADD COLUMN IF NOT EXISTS max_calls_total BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_calls_daily BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS call_count_total BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS call_count_daily BIGINT DEFAULT 0;
