ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS balance_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS paypal_fee_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stripe_fee_rate DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS orders
  ADD COLUMN IF NOT EXISTS channel_fee_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS channel_fee DOUBLE PRECISION NOT NULL DEFAULT 0;
