ALTER TABLE products
  DROP COLUMN IF EXISTS label,
  DROP COLUMN IF EXISTS payment_method,
  DROP COLUMN IF EXISTS sandbox,
  DROP COLUMN IF EXISTS total_used,
  DROP COLUMN IF EXISTS last_used_at;

ALTER TABLE orders
  DROP COLUMN IF EXISTS product_id,
  DROP COLUMN IF EXISTS b_transaction_id,
  DROP COLUMN IF EXISTS email,
  DROP COLUMN IF EXISTS ip,
  DROP COLUMN IF EXISTS risk_score,
  DROP COLUMN IF EXISTS payment_method,
  DROP COLUMN IF EXISTS currency;

ALTER TABLE users
  DROP COLUMN IF EXISTS product_strategy;
